name: Build Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag imageappangular:latest .

#name: Build and Push Docker Image

#on:
  #push:
    #branches:
      #- master

#jobs:
  #build-and-push:
    #runs-on: ubuntu-latest

    #steps:
      #- name: Checkout Repository
        #uses: actions/checkout@v2

      #- name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v1

      #- name: Login to Docker Hub
        #uses: docker/login-action@v1
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build Docker Image
        #run: |
          #docker buildx build \
            #--platform linux/amd64,linux/arm64 \
            #--push \
            #--tag yourdockerusername/yourimagename:latest .
