name: Build Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true


jobs:
  build_angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install
        
      #- name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "icicabz"
          password: "Devops123"
          
      - name: Build Docker image for Angular
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Web_app-Angular/Dockerfile
          push: true
          tags: icicabz/imageappangular:latest

  build_dotnet:
    name: Build and Deploy .NET Core API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build API
        run: dotnet build --configuration Release

      - name: Publish API
        run: dotnet publish --configuration Release --output ./publish

      - name: Build Docker image for API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Web_API-.NET/Dockerfile
          push: true
          tags: icicabz/imageapidotnet:latest

  deploy_with_docker_compose:
    name: Deploy with Docker Compose
    runs-on: ubuntu-latest
    needs: 
      - build_angular
      - build_dotnet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        uses: actions/setup-docker@v2
        with:
          docker-version: '20.10.8'  # Version de Docker à installer

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "icicabz"
          password: "Devops123"

      - name: Pull Docker images
        run: docker-compose pull

      - name: Start Docker Compose services
        run: docker-compose up -d

#name: Build and Push Docker Image

#on:
  #push:
    #branches:
      #- master

#jobs:
  #build-and-push:
    #runs-on: ubuntu-latest

    #steps:
      #- name: Checkout Repository
        #uses: actions/checkout@v2

      #- name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v1

      #- name: Login to Docker Hub
        #uses: docker/login-action@v1
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build Docker Image
        #run: |
          #docker buildx build \
            #--platform linux/amd64,linux/arm64 \
            #--push \
            #--tag yourdockerusername/yourimagename:latest .
